CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR                                             NOT NULL,
    email VARCHAR                                             NOT NULL,
    CONSTRAINT user_email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    description  VARCHAR,
    requestor_id BIGINT REFERENCES users (id),
    created      DATE
);

CREATE TABLE IF NOT EXISTS items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name            VARCHAR                                             NOT NULL,
    description     VARCHAR,
    available       BOOLEAN,
    owner_id        BIGINT REFERENCES users (id) ON DELETE CASCADE,
    item_request_id BIGINT REFERENCES item_requests (id)
);